In [13]:
import pandas as pd

In [14]:
df_ionosphere = pd.read_csv('/home/gui/Documents/2_experimentos_pesquisa-20230815T143457Z-001/experimentos_pesquisa/Resultados/dataframe_Ionosphere.csv')
df_ionosphere.head()

  Algoritmo  Iteração  Rate       acc        f1  RN len  tempo de execução
0    LP_PUL         0  0.01  0.100000  0.181818      50           0.142271
1     CCRNE         0  0.01  0.285156  0.443769     256           0.014357
2    AE_PUL         0  0.01  0.940000  0.969072      50           0.375201
3   GAE_PUL         0  0.01  0.940000  0.969072      50           1.246668
4      MCLS         0  0.01  0.220000  0.360656      50           0.564860

In [15]:
df_ionosphere.loc[df_ionosphere['Algoritmo'] == 'GAE_PUL',:]

    Algoritmo  Iteração  Rate   acc        f1  RN len  tempo de execução
3     GAE_PUL         0  0.01  0.94  0.969072      50           1.246668
10    GAE_PUL         1  0.01  0.88  0.936170      50           1.152075
17    GAE_PUL         2  0.01  0.76  0.863636      50           1.224618
24    GAE_PUL         3  0.01  0.72  0.837209      50           0.984589
31    GAE_PUL         4  0.01  0.98  0.989899      50           1.634682
..        ...       ...   ...   ...       ...     ...                ...
598   GAE_PUL         5  0.25  0.64  0.780488      50           0.745081
605   GAE_PUL         6  0.25  0.66  0.795181      50           0.748588
612   GAE_PUL         7  0.25  0.90  0.947368      50           0.763656
619   GAE_PUL         8  0.25  0.82  0.901099      50           0.821406
626   GAE_PUL         9  0.25  0.70  0.823529      50           0.761822

[90 rows x 7 columns]

In [18]:
compacacao = df_ionosphere.loc[df_ionosphere['Algoritmo'] == 'GAE_PUL',:]['f1'] == df_ionosphere.loc[df_ionosphere['Algoritmo'] == 'AE_PUL',:]['f1']

ValueError: Can only compare identically-labeled Series objects

In [35]:
s1 = df_ionosphere.loc[df_ionosphere['Algoritmo'] == 'GAE_PUL',:]['f1']
s1.reset_index()

    index        f1
0       3  0.969072
1      10  0.936170
2      17  0.863636
3      24  0.837209
4      31  0.989899
..    ...       ...
85    598  0.780488
86    605  0.795181
87    612  0.947368
88    619  0.901099
89    626  0.823529

[90 rows x 2 columns]

In [32]:
df_ionosphere.loc[df_ionosphere['Algoritmo'] == 'AE_PUL',:]['f1'].reset_index

<bound method Series.reset_index of 2      0.969072
9      0.924731
16     0.876404
23     0.837209
30     0.979592
         ...
597    0.765432
604    0.780488
611    0.958333
618    0.901099
625    0.837209
Name: f1, Length: 90, dtype: float64>